ignore:
  - "core-customize/hybris/bin/custom/sapcxtools/**/backoffice/src/**/*"
  - "core-customize/hybris/bin/custom/sapcxtools/**/gensrc/**/*"
  - "core-customize/hybris/bin/custom/sapcxtools/**/testsrc/**/*"
