ignore:
  - "hybris/bin/custom/sapcxtools/*/backoffice/src/**/*"
  - "hybris/bin/custom/sapcxtools/*/backoffice/testsrc/**/*"
  - "hybris/bin/custom/sapcxtools/*/gensrc/**/*"
  - "hybris/bin/custom/sapcxtools/*/testsrc/**/*"
